# Generated by Django 4.2.2 on 2024-10-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_weekday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='periodicity',
        ),
        migrations.AddField(
            model_name='habit',
            name='periodicity',
            field=models.ManyToManyField(default=1, related_name='habits', to='habits.weekday', verbose_name='Дни недели'),
        ),
    ]
