# Generated by Django 4.2.2 on 2024-10-31 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_remove_habit_periodicity_habit_periodicity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='periodicity',
            new_name='weekdays',
        ),
    ]
