# Generated by Django 4.2.2 on 2024-10-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_rename_periodicity_habit_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последней отправки уведомления'),
        ),
    ]
